### ISSUE TITLE
Extend FrameLayout

### ISSUE THREAD

**Issue by consp1racy** [harjot-oberai/MaterialShadows#3]
RelativeLayout always performs view measurement twice. Since this widget is intended for small views FrameLayout is more efficient and covers most simple use cases e.g. an image with an overlay in one corner.

**Comment by doriandarren** [comment]
Sorry! don't understand the cuestion

**Comment by consp1racy** [comment]
It's not a question, it's a suggestion to make the library more efficient.

See here https://stackoverflow.com/questions/4069037/is-a-relativelayout-more-expensive-than-a-linearlayout

`MaterialShadowViewWrapper` should extend `FrameLayout`.

**Comment by harjot-oberai** [comment]
If a user wants multiple views with the same shadow parameters, that is achievable by putting all the views inside the Wrapper itself. Having different shadow parameters for different views is not good by design point of view as well (not always, but generally), so the most common use case will be to have views with same shadow parameters, that's why I used Relative layout as the super class.
That said, I am working on creating a new wrapper that will extend 'FrameLayout' to address this issue as well.

**Comment by consp1racy** [comment]
In Limitations in README you say that

> Currently the shadow is generated only for direct children of the `MaterialShadowViewWrapper`.

That's perfectly ok.

---

> That said, I am working on creating a new wrapper that will extend 'FrameLayout' to address this issue as well.

I agree completely. Please refactor so that the shadow functionality can be easily plugged into any custom or platform ViewGroup.

**Comment by harjot-oberai** [comment]
I have updated the code and added a new wrapper that extends `FrameLayout`. Also, I have encapsulated all the shadow generation related code into a single class and updated the README to explain how to use it with custom ViewGroups.

See [here](https://github.com/harjot-oberai/MaterialShadows/blob/master/README.md#using-materialshadows-with-custom-viewgroups).
