### ISSUE TITLE
minSdkVersion must be 21+？

### ISSUE THREAD

**Issue by FynnJason** [harjot-oberai/MaterialShadows#4]
I use minSdkVersion is 19,
The system is then prompted to add the following statement to the registry：
tools:overrideLibrary="com.sdsmdg.harjot.materialshadows".
But the system hints are still there.

**Comment by harjot-oberai** [comment]
The `ViewOutlineProvider` and the `Outline` classes that are used for generating the shadows were added in API 21, so the library would not work below API 21.
The system hints are there because of the IDE as the classes from the library have been added to your project. If you try to run the application on API 19 or 20, the app will crash or give some unexpected result.
